name: Insertion sort Tests
on:
  push:
    branches:
      - pratik-6sept/insertion_test
  pull_request:
    branches:
      - pratik-6sept/insertion_test

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.6
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests with pytest
        run: pytest 